# Importing Libraries 

In [3]:
import numpy as np
import pandas as pd

In [4]:
data=pd.read_csv('Data.csv')

In [5]:
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [6]:
data.iloc[0:8, 0:3]

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0

In [7]:
data.iloc[2:8, 1:3]

Age   Salary
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  52000.0
7  48.0  79000.0

In [8]:
data.iloc[:, 3]

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [9]:
data.iloc[1:5, -1]

1    Yes
2     No
3     No
4    Yes
Name: Purchased, dtype: object

# Taking Care of missing Values

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
#from sklearn.impute import SimpleImputer

# 'np.nan' signifies that we are targeting missing values
# and the strategy we are choosing is replacing it with 'mean'
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer.fit(data.iloc[:, 1:3])
data.iloc[:, 1:3] = imputer.transform(data.iloc[:, 1:3])

# print the dataset
#data.head()
print(data)


   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes


# Encoding categorical data

# OneHotenconding

we'll name the transformer 

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# [0] signifies the index of the column we are appliying the encoding on
data = pd.DataFrame(ct.fit_transform(data))
print(data)
#data.head()

     0    1    2          3             4    5
0  1.0  0.0  0.0       44.0       72000.0   No
1  0.0  0.0  1.0       27.0       48000.0  Yes
2  0.0  1.0  0.0       30.0       54000.0   No
3  0.0  0.0  1.0       38.0       61000.0   No
4  0.0  1.0  0.0       40.0  63777.777778  Yes
5  1.0  0.0  0.0       35.0       58000.0  Yes
6  0.0  0.0  1.0  38.777778       52000.0   No
7  1.0  0.0  0.0       48.0       79000.0  Yes
8  0.0  1.0  0.0       50.0       83000.0   No
9  1.0  0.0  0.0       37.0       67000.0  Yes


# LabelEncoding

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data.iloc[:,-1] = le.fit_transform(data.iloc[:,-1])
print(data)

     0    1    2          3             4  5
0  1.0  0.0  0.0       44.0       72000.0  0
1  0.0  0.0  1.0       27.0       48000.0  1
2  0.0  1.0  0.0       30.0       54000.0  0
3  0.0  0.0  1.0       38.0       61000.0  0
4  0.0  1.0  0.0       40.0  63777.777778  1
5  1.0  0.0  0.0       35.0       58000.0  1
6  0.0  0.0  1.0  38.777778       52000.0  0
7  1.0  0.0  0.0       48.0       79000.0  1
8  0.0  1.0  0.0       50.0       83000.0  0
9  1.0  0.0  0.0       37.0       67000.0  1


# Normalizing the Data

MinMaxscaler scales all the data features

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data = pd.DataFrame(scaler.fit_transform(data))
print(data)

     0    1    2         3         4    5
0  1.0  0.0  0.0  0.739130  0.685714  0.0
1  0.0  0.0  1.0  0.000000  0.000000  1.0
2  0.0  1.0  0.0  0.130435  0.171429  0.0
3  0.0  0.0  1.0  0.478261  0.371429  0.0
4  0.0  1.0  0.0  0.565217  0.450794  1.0
5  1.0  0.0  0.0  0.347826  0.285714  1.0
6  0.0  0.0  1.0  0.512077  0.114286  0.0
7  1.0  0.0  0.0  0.913043  0.885714  1.0
8  0.0  1.0  0.0  1.000000  1.000000  0.0
9  1.0  0.0  0.0  0.434783  0.542857  1.0


# Splitting the dataset

In [15]:
X = data.iloc[:, :5].values #X = data.iloc[:, :-1].values
y = data.iloc[:, 5].values #y = data.iloc[:, -1].values
print("Independent Variable\n")
print(X)
print("\nDependent Variable\n")
print(y)

Independent Variable

[[1.         0.         0.         0.73913043 0.68571429]
 [0.         0.         1.         0.         0.        ]
 [0.         1.         0.         0.13043478 0.17142857]
 [0.         0.         1.         0.47826087 0.37142857]
 [0.         1.         0.         0.56521739 0.45079365]
 [1.         0.         0.         0.34782609 0.28571429]
 [0.         0.         1.         0.51207729 0.11428571]
 [1.         0.         0.         0.91304348 0.88571429]
 [0.         1.         0.         1.         1.        ]
 [1.         0.         0.         0.43478261 0.54285714]]

Dependent Variable

[0. 1. 0. 0. 1. 1. 0. 1. 0. 1.]


In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0) #or 0

In [54]:
print(X_train)


[[0.         1.         0.         0.56521739 0.45079365]
 [1.         0.         0.         0.43478261 0.54285714]
 [0.         0.         1.         0.         0.        ]
 [0.         0.         1.         0.51207729 0.11428571]
 [1.         0.         0.         0.91304348 0.88571429]
 [0.         0.         1.         0.47826087 0.37142857]
 [1.         0.         0.         0.73913043 0.68571429]
 [1.         0.         0.         0.34782609 0.28571429]]


In [55]:
print(X_test)

[[0.         1.         0.         0.13043478 0.17142857]
 [0.         1.         0.         1.         1.        ]]


In [56]:
print(y_train)

[1. 1. 1. 0. 1. 0. 0. 1.]


In [57]:
print(y_test)


[0. 0.]


In [ ]:
@Hibarere  X = data.iloc[:, :5].values #X = data.iloc[:, :-1].values
y = data.iloc[:, 5].values #y = data.iloc[:, -1].values
print("Independent Variable\n")
print(X)
print("\nDependent Variable\n")
print(y)